# Generated by Django 4.0.3 on 2022-04-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
    ]
